---
- name: Deploy and Configure Glances
  hosts: "{{ target_host }}"
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Fail if required variables are not provided
      ansible.builtin.fail:
        msg: "The 'target_host' variable must be set. Use -e 'target_host=...'"
      when: target_host is not defined or target_host | length == 0

    - name: Create a dedicated system user for Glances
      ansible.builtin.user:
        name: glances
        system: yes
        create_home: yes
        home: /home/glances
        shell: /usr/sbin/nologin

    - name: Install prerequisite packages
      ansible.builtin.apt:
        name:
          - build-essential
          - python3-dev
          - pipx
          - acl
          - python3-pexpect
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Glances using pipx
      become_user: glances
      ansible.builtin.command:
        cmd: "pipx install 'glances[all]'"
        creates: /home/glances/.local/bin/glances

    - name: Ensure old password file if it exists
      become: yes
      ansible.builtin.file:
        path: /home/glances/.config/glances/glances.pwd
        state: absent

    - name: Generate the glances.pwd file using expect
      become_user: glances
      ansible.builtin.expect:
        command: "/home/glances/.local/bin/glances -w --password"
        responses:
          "Define the Glances webserver password": "{{ glances_pass }}"
          "Password (confirm)": "{{ glances_pass }}"
          "save the password?": "Yes"
        timeout: 20
      #no_log: true # Prevents password from appearing in logs

    - name: Create Systemd unit file
      ansible.builtin.copy:
        dest: /etc/systemd/system/glances.service
        owner: root
        group: root
        mode: "0644"
        content: |
          [Unit]
          Description=Glances Monitoring Tool
          After=network.target

          [Service]
          WorkingDirectory=/home/glances
          ExecStart=/home/glances/.local/bin/glances -w -B 0.0.0.0 --password -t 30 # For single core systems, it can be useful to limit the refresh/polling rate for measurements. In this case it is set to 30 seconds.
          Restart=always
          RemainAfterExit=no
          User=glances
          Group=glances

          [Install]
          WantedBy=multi-user.target
      notify: Restart Glances

    - name: Ensure Glances service is running and enabled on boot
      ansible.builtin.systemd:
        name: glances
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Force handler to run immediately
      ansible.builtin.meta: flush_handlers

    - name: Verify that the Glances web service is responding
      ansible.builtin.uri:
        url: "http://localhost:61208"
        method: GET
        status_code: 200
        user: glances
        password: "{{ glances_pass }}"
        force_basic_auth: yes
      register: glances_health_check
      until: glances_health_check.status == 200
      retries: 5
      delay: 3

  handlers:
    - name: Restart Glances
      ansible.builtin.systemd:
        name: glances
        state: restarted
