---
- name: Deploy and Configure Glances
  hosts: "{{ target_host }}"
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Fail if required variables are not provided
      ansible.builtin.fail:
        msg: "The 'target_host' variable must be set. Use -e 'target_host=...'"
      when: target_host == ""

    - name: Create a dedicated system user for Glances
      ansible.builtin.user:
        name: glances
        system: yes
        create_home: yes
        home: /home/glances
        shell: /usr/sbin/nologin

    - name: Update apt cache (Debian-based systems)
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
      changed_when: false

    - name: Install Glances using the native package manager
      ansible.builtin.package:
        name: glances
        state: present

    - name: Install bottle for the web server mode
      ansible.builtin.package:
        name: python3-bottle
        state: present

    - name: Create Systemd unit file
      ansible.builtin.copy:
        dest: /etc/systemd/system/glances.service
        owner: root
        group: root
        mode: "0644"
        content: |
          [Unit]
          Description=Glances Monitoring Tool
          After=network.target

          [Service]
          WorkingDirectory=/home/glances
          ExecStart=/usr/bin/glances -w -B 0.0.0.0
          Restart=always
          RemainAfterExit=no
          User=glances
          Group=glances

          [Install]
          WantedBy=multi-user.target
      notify: Restart Glances

    - name: Ensure Glances service is running and enabled on boot
      ansible.builtin.systemd:
        name: glances
        state: started
        enabled: yes
        daemon_reload: yes

  handlers:
    - name: Restart Glances
      ansible.builtin.systemd:
        name: glances
        state: restarted
